Repository openthread/wpantund, pull requests merged in 2018-10, with the labels that each got.

#350 Add a common method to log sent/received spinel frame info
  src/ncp-spinel/SpinelNCPInstance-DataPump.cpp
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/ncp-spinel/SpinelNCPInstance.h
Labels: P4, enhancement

#355 Update how the SLAAC addresses are removed
  src/wpantund/NCPInstanceBase-Addresses.cpp
  src/wpantund/NCPInstanceBase.h
Labels: P4, bug

#357 Add new property to get list of NCP capabilities
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/ncp-spinel/SpinelNCPInstance.h
  src/wpantund/wpan-properties.h
Labels: P4, enhancement

#359 Fix "use after delete issue" in on_mesh_prefix_was_removed
  src/wpantund/NCPInstanceBase-Addresses.cpp
Labels: P3, bug

#361 Add new property "POSIXApp:RCPVersion"
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/wpantund/wpan-properties.h
  third_party/openthread/src/ncp/spinel.c
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#362 Do not use glibc-internal header sys/cdefs.h
  src/ncp-spinel/spinel-extra.h
  src/util/config-file.h
  src/util/netif-mgmt.h
  src/util/nlpt-select.h
  src/util/sec-random.h
  src/util/socket-utils.h
  src/util/string-utils.h
  src/util/time-utils.h
  src/util/tunnel.h
  src/version.h
  src/wpantund/wpan-error.h
  src/wpantund/wpantund.cpp
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement
