Repository openthread/wpantund, pull requests merged in 2018-06, with the labels that each got.

#305 Add new wpan property "Thread:RouterSelectionJitter"
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/wpantund/wpan-properties.h
Labels: P4, enhancement

#303 Fix mistakes in bootstrap.sh
  bootstrap.sh
Labels: enhancement

#308 Add support for Android build system
  Android.mk
  src/ipc-dbus/DBusIPCAPI_v0.cpp
  src/ipc-dbus/DBusIPCAPI_v1.cpp
  src/wpantund/NCPMfgInterface_v0.h
  src/wpantund/NCPMfgInterface_v1.h
Labels: P2, feature

#310 Adding properties to get/set Thread Router Upgrade/Downgrade Threshold
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/wpantund/wpan-properties.h
Labels: P4, enhancement

#307 Add new property "Thread:AddressCacheTable"
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/wpantund/wpan-properties.h
  third_party/openthread/src/ncp/spinel.c
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#312 Adding new property "Network:KeySwitchGuardTime"
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/wpantund/wpan-properties.h
Labels: P4, enhancement

#313 Persist the user-set "Thread:DeviceMode" property value over NCP resets
  src/ncp-spinel/SpinelNCPInstance.cpp
Labels: P4, enhancement

#315 Remove extra `dbus_message_ref()` in DBus APIs methods
  src/ipc-dbus/DBusIPCAPI_v0.cpp
  src/ipc-dbus/DBusIPCAPI_v1.cpp
Labels: P4, bug

#318 Eliminate running bootstrap on android
  Android.mk
Labels: P1

#316 New APIs for adding/removing on-mesh prefix
  src/ipc-dbus/DBusIPCAPI_v0.cpp
  src/ipc-dbus/DBusIPCAPI_v1.cpp
  src/ncp-dummy/DummyNCPControlInterface.cpp
  src/ncp-dummy/DummyNCPControlInterface.h
  src/ncp-spinel/SpinelNCPControlInterface.cpp
  src/ncp-spinel/SpinelNCPControlInterface.h
  src/wpanctl/Makefile.am
  src/wpanctl/tool-cmd-add-prefix.c
  src/wpanctl/tool-cmd-add-prefix.h
  src/wpanctl/tool-cmd-config-gateway.c
  src/wpanctl/tool-cmd-remove-prefix.c
  src/wpanctl/tool-cmd-remove-prefix.h
  src/wpanctl/wpanctl-cmds.h
  src/wpantund/NCPControlInterface.h
  src/wpantund/NCPInstanceBase-Addresses.cpp
  src/wpantund/NCPInstanceBase.h
Labels: P4, enhancement

#317 Add support to specify "stable" flag for off-mesh routes
  src/ipc-dbus/DBusIPCAPI_v0.cpp
  src/ipc-dbus/DBusIPCAPI_v1.cpp
  src/ncp-dummy/DummyNCPControlInterface.cpp
  src/ncp-dummy/DummyNCPControlInterface.h
  src/ncp-spinel/SpinelNCPControlInterface.cpp
  src/ncp-spinel/SpinelNCPControlInterface.h
  src/wpanctl/tool-cmd-add-route.c
  src/wpanctl/tool-cmd-remove-route.c
  src/wpantund/NCPControlInterface.h
Labels: P4, enhancement

#323 Add spi-hdlc-adapter to Android.mk
  Android.mk
Labels: P4, android, enhancement

#324 Sync spi-hdlc-adapter to OpenThread commit 60fc0ac0
  third_party/openthread/tools/spi-hdlc-adapter/README.md
  third_party/openthread/tools/spi-hdlc-adapter/spi-hdlc-adapter.c
Labels: P4, enhancement
