Repository openthread/wpantund, pull requests merged in 2018-04, with the labels that each got.

#291 Fix incorrect comparision in `SpinelNCPTaskGetNetworkTopology`
  src/ncp-spinel/SpinelNCPTaskGetNetworkTopology.cpp
Labels: P3, bug

#287 Implement properties related to "Channel Manager" OT feature
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/ncp-spinel/SpinelNCPInstance.h
  src/wpantund/wpan-properties.h
  third_party/openthread/src/ncp/spinel.c
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#289 Add support for NCP MCU power state control and deep-sleep mode
  src/ncp-spinel/SpinelNCPControlInterface.cpp
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/ncp-spinel/SpinelNCPTaskDeepSleep.cpp
  src/ncp-spinel/SpinelNCPTaskWake.cpp
  src/wpantund/wpan-properties.h
  third_party/openthread/src/ncp/spinel.c
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#293 Allow auto-resume from wpan "offline:deep-sleep" state
  src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
Labels: P4, enhancement

#292 Enabling "toranj" test-framework on wpantund travis CI
  .travis.yml
  .travis/script.sh
Labels: P4, continuous-integration, enhancement

#295 Disable ncp-spinel-fuzz target
  src/ncp-spinel/Makefile.am
Labels: P4, enhancement

#294 Enable adding/removing multicast IPv6 addresses
  src/wpantund/NCPInstanceBase-Addresses.cpp
  src/wpantund/NCPInstanceBase.cpp
  src/wpantund/NCPInstanceBase.h
Labels: P4, enhancement

#296 Replace an unchecked strcpy with a better strncpy
  src/connman-plugin/wpan-connman-plugin.c
Labels: P4, enhancement
