Repository openthread/wpantund, pull requests merged in 2018-05, with the labels that each got.

#297 Add spi-hdlc-adapater socket example in wpantund.conf sample
  src/wpantund/wpantund.conf
Labels: P4, documentation, enhancement

#298 Update spinel header files
  src/ncp-spinel/SpinelNCPInstance.cpp
  third_party/openthread/src/ncp/spinel.c
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#300 Allow NCP reset to restart the initialization protothread earlier
  src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
Labels: P3, enhancement

#301 spinel: Added new SpinelNCPVendorCustom class
  src/ncp-spinel/Makefile.am
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/ncp-spinel/SpinelNCPInstance.h
  src/ncp-spinel/SpinelNCPVendorCustom.cpp
  src/ncp-spinel/SpinelNCPVendorCustom.h
Labels: enhancement

#299 Add support for new NCP log output model and spinel property
  src/ncp-spinel/SpinelNCPInstance-DataPump.cpp
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/ncp-spinel/SpinelNCPInstance.h
  third_party/openthread/src/ncp/spinel.c
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#302 spinel: Remove dead code related to setting Network Key
  src/ncp-spinel/SpinelNCPInstance.cpp
Labels: P3, task
