Repository openthread/wpantund, pull requests merged in 2018-08, with the labels that each got.

#336 Adding support for "Child Supervision" properties in wpantund
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/wpantund/wpan-properties.h
  third_party/openthread/src/ncp/spinel.c
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#338 Fix the `encode_data_into_string()` implementation
  src/util/string-utils.c
Labels: P3, bug

#339 Enter ISOLATED state after resume on a sleepy child
  src/ncp-spinel/SpinelNCPInstance.cpp
Labels: P4, enhancement

#340 Update wpanctl `form` and `join` implementation to use DBus v1 APIs
  src/wpanctl/tool-cmd-form.c
  src/wpanctl/tool-cmd-join.c
  src/wpanctl/wpanctl-utils.c
  src/wpanctl/wpanctl-utils.h
Labels: P4, enhancement

#331 Remove using DBUS_BUS_STARTER
  src/ipc-dbus/DBUSIPCServer.cpp
  src/wpanctl/tool-cmd-add-prefix.c
  src/wpanctl/tool-cmd-add-route.c
  src/wpanctl/tool-cmd-begin-low-power.c
  src/wpanctl/tool-cmd-begin-net-wake.c
  src/wpanctl/tool-cmd-commissioner.c
  src/wpanctl/tool-cmd-commr.c
  src/wpanctl/tool-cmd-config-gateway.c
  src/wpanctl/tool-cmd-dataset.c
  src/wpanctl/tool-cmd-form.c
  src/wpanctl/tool-cmd-getprop.c
  src/wpanctl/tool-cmd-host-did-wake.c
  src/wpanctl/tool-cmd-join.c
  src/wpanctl/tool-cmd-joiner.c
  src/wpanctl/tool-cmd-leave.c
  src/wpanctl/tool-cmd-list.c
  src/wpanctl/tool-cmd-mfg.c
  src/wpanctl/tool-cmd-pcap.c
  src/wpanctl/tool-cmd-peek.c
  src/wpanctl/tool-cmd-permit-join.c
  src/wpanctl/tool-cmd-poke.c
  src/wpanctl/tool-cmd-poll.c
  src/wpanctl/tool-cmd-remove-prefix.c
  src/wpanctl/tool-cmd-remove-route.c
  src/wpanctl/tool-cmd-reset.c
  src/wpanctl/tool-cmd-resume.c
  src/wpanctl/tool-cmd-scan.c
  src/wpanctl/tool-cmd-status.c
  src/wpanctl/tool-updateprop.c
  src/wpanctl/wpanctl-utils.c
  src/wpanctl/wpanctl.c
Labels: P3, enhancement

#343 Enhance android makefile
  .travis.yml
  .travis/android_check
  .travis/before_install.sh
  .travis/script.sh
  Android.mk
Labels: P3, android, enhancement
