Repository openthread/wpantund, pull requests merged in 2018-07, with the labels that each got.

#320 Enable setting of "NCP:ChannelMask"
  src/ncp-spinel/SpinelNCPControlInterface.cpp
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/ncp-spinel/SpinelNCPInstance.h
  src/ncp-spinel/SpinelNCPTaskForm.cpp
  src/wpantund/NCPInstanceBase.h
Labels: P4, enhancement

#321 Include "string-utils.h" in tool-cmd-poke and tool-cmd-dataset
  src/util/string-utils.h
  src/wpanctl/tool-cmd-dataset.c
  src/wpanctl/tool-cmd-poke.c
  src/wpantund/wpantund.cpp
Labels: P4, enhancement

#326 Add wpan property "Thread:Parent" to get parent info
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/wpantund/wpan-properties.h
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#328 Remove redundant checks of unsigned with zero in add-route/remove-roue commands
  src/wpanctl/tool-cmd-add-route.c
  src/wpanctl/tool-cmd-remove-route.c
Labels: P4, enhancement

#329 Update spinel definition from OpenThread
  third_party/openthread/src/ncp/spinel.c
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#309 Replace TMF proxy with UDP proxy
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/wpantund/wpan-properties.h
  third_party/openthread/src/ncp/spinel.h
Labels: P3, enhancement, feature

#327 Add support for sending MGMT_GET for Active/Pending Dataset
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/ncp-spinel/SpinelNCPThreadDataset.cpp
  src/ncp-spinel/SpinelNCPThreadDataset.h
  src/wpanctl/tool-cmd-dataset.c
  src/wpantund/wpan-properties.h
  third_party/openthread/src/ncp/spinel.c
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#335 Update spinel header files from OpenThread
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#334 Allow multiple instances of same on-mesh prefix to be tracked separately
  src/ncp-spinel/SpinelNCPControlInterface.cpp
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/ncp-spinel/SpinelNCPInstance.h
  src/wpantund/NCPInstanceBase-Addresses.cpp
  src/wpantund/NCPInstanceBase.cpp
  src/wpantund/NCPInstanceBase.h
Labels: P4, bug, enhancement
