Repository openthread/wpantund, pull requests merged in 2019-06, with the labels that each got.

#417 Parse an empty DBUs message as an empty ValueMap dictionary
  src/util/DBUSHelpers.cpp
Labels: P4, bug

#415 Log neighbor/router entry added/removed events from NCP
  src/ncp-spinel/SpinelNCPInstance.cpp
Labels: P4, enhancement

#418 Update spinel files from OpenThread
  third_party/openthread/src/ncp/spinel.c
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#420 Update spinel files from OpenThread (#418)
  third_party/openthread/src/ncp/spinel.c
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#423 Add option to expect reset on start
  Android.mk
  src/ncp-spinel/SpinelNCPInstance.cpp
Labels: P1, enhancement
