Repository openthread/wpantund, pull requests merged in 2019-04, with the labels that each got.

#395 Update spinel files from OpenThread
  third_party/openthread/src/ncp/spinel.c
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#397 "Thread:Joiner:State" returning string
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/wpantund/wpan-properties.h
  third_party/openthread/src/ncp/spinel.h
Labels: P4, enhancement

#386 Add ALOC service support
  src/ipc-dbus/DBusIPCAPI_v1.cpp
  src/ipc-dbus/DBusIPCAPI_v1.h
  src/ipc-dbus/wpan-dbus-v1.h
  src/ncp-dummy/DummyNCPControlInterface.cpp
  src/ncp-dummy/DummyNCPControlInterface.h
  src/ncp-dummy/DummyNCPInstance.cpp
  src/ncp-dummy/DummyNCPInstance.h
  src/ncp-spinel/SpinelNCPControlInterface.cpp
  src/ncp-spinel/SpinelNCPControlInterface.h
  src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp
  src/ncp-spinel/SpinelNCPInstance.cpp
  src/ncp-spinel/SpinelNCPInstance.h
  src/wpanctl/Makefile.am
  src/wpanctl/tool-cmd-add-service.c
  src/wpanctl/tool-cmd-add-service.h
  src/wpanctl/tool-cmd-remove-service.c
  src/wpanctl/tool-cmd-remove-service.h
  src/wpanctl/wpanctl-cmds.h
  src/wpantund/NCPControlInterface.h
  src/wpantund/NCPInstanceBase-Addresses.cpp
  src/wpantund/NCPInstanceBase.cpp
  src/wpantund/NCPInstanceBase.h
  src/wpantund/wpan-properties.h
  third_party/openthread/src/ncp/spinel.c
Labels: P4, enhancement

#401 [wpanctl] switch to service user
  configure.ac
  src/wpanctl/wpanctl.c
Labels: P4, enhancement

#405 [build] add missing virtual destructors
  src/wpantund/NCPInstanceBase.h
Labels: P2, enhancement

#404 [android] use monotonic time
  Android.mk
Labels: P2, bug

#403 Update Joiner support (enable blocking mode and return joiner error)
  src/ncp-spinel/SpinelNCPTaskJoinerCommissioning.cpp
  src/ncp-spinel/SpinelNCPTaskJoinerCommissioning.h
  src/wpanctl/tool-cmd-joiner.c
  src/wpantund/NCPConstants.h
  src/wpantund/wpan-error.c
  src/wpantund/wpan-error.h
  src/wpantund/wpan-properties.h
Labels: P4, enhancement
